version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.10
    steps:
      - checkout
      - run:
          name: Terraform Init  
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
